### ISSUE TITLE
Adding `RateLimitLayer` results in a compilation error

### ISSUE THREAD

**Issue by IgnisDa** [geofmureithi/apalis#297] opened 2024-04-21 17:32 UTC
I am not sure why the error happens, but as soon as I remove the `RateLimitLayer`, the error disappears.

![image](https://github.com/geofmureithi/apalis/assets/60938164/816e7cac-516a-48e2-887b-b47af853eae2)

Here is what the code looks like:

```rs
           .register_with_count(3, {
                WorkerBuilder::new("perform_application_job")
                    .layer(ApalisRateLimitLayer::new(
                        rate_limit_num,
                        Duration::new(5, 0),
                    ))
                    .layer(ApalisTraceLayer::new())
                    .data(importer_service_1.clone())
                    .data(exporter_service_1.clone())
                    .data(media_service_4.clone())
                    .data(exercise_service_1.clone())
                    .with_storage(perform_application_job_storage.clone())
                    .build_fn(perform_application_job)
            })
```

**Comment by IgnisDa** [comment] 2024-04-21 17:33
Tried changing the order of layers, count from 3 -> 1. Did not work.

**Comment by IgnisDa** [comment] 2024-04-21 17:36
https://github.com/IgnisDa/ryot/blob/b9019dfa1f5948c071857a076ac7e14146d592d8/apps/backend/src/main.rs#L310-L322 are the lines if you are interested.

**Comment by geofmureithi** [comment] 2024-04-22 05:31
Could you try to check clone and check service clone?
https://docs.rs/tower/latest/tower/builder/struct.ServiceBuilder.html#method.check_clone

You can access the service builder using WorkerBuilder.chain

**Comment by IgnisDa** [comment] 2024-04-22 05:44
@geofmureithi I am not sure what I need to do with the methods you gave. I added them to my code, it didn't change the error.

**Comment by geofmureithi** [comment] 2024-04-22 05:51
Have you checked this issue?
https://github.com/geofmureithi/apalis/discussions/256

**Comment by geofmureithi** [comment] 2024-04-22 06:00
See also
https://github.com/tokio-rs/axum/discussions/987#discussioncomment-2678595

The issue is that from 0.5 apalis needs the service to be clone yet tower rate limit is not clone.

The suggested option is to include BufferLayer infront of the rate limit one.

**Comment by IgnisDa** [comment] 2024-04-22 06:06
> The suggested option is to include BufferLayer infront of the rate limit one.

I did that, still does not work. The error has changed:
![image](https://github.com/geofmureithi/apalis/assets/60938164/57685595-3320-4efd-bf22-8496e40c9bfd)

**Comment by geofmureithi** [comment] 2024-04-22 06:53
Seems the issue here is with tower.
Can you try using `.chain`
Can you also try using a custom implementation eg https://medium.com/@khalludi123/creating-a-rate-limiter-middleware-using-tower-for-axum-rust-be1d65fbeca

**Comment by IgnisDa** [comment] 2024-04-22 06:58
Got it working with:

```rs
            .register_with_count(
                1,
                WorkerBuilder::new("perform_application_job")
                    .data(importer_service_1.clone())
                    .data(exporter_service_1.clone())
                    .data(media_service_4.clone())
                    .data(exercise_service_1.clone())
                    .with_storage(perform_application_job_storage.clone())
                    .chain(|s| {
                        s.layer(BufferLayer::new(1024))
                            .layer(ApalisRateLimitLayer::new(
                                rate_limit_num,
                                Duration::new(5, 0),
                            ))
                            .layer(ApalisTraceLayer::new())
                    })
                    .build_fn(perform_application_job),
            )
```

Should I keep this issue open? (Since I had to use a workaround).

**Comment by geofmureithi** [comment] 2024-04-22 07:01
I will check the problem then close it.

**Comment by IgnisDa** [comment] 2024-04-22 07:06
Cool! Thanks for your guidance.

**Comment by IgnisDa** [comment] 2024-05-24 11:46
@geofmureithi Any updates on this?

**Comment by IgnisDa** [comment] 2024-06-29 17:57
@geofmureithi Sorry for the ping. Were you able to find the problem?

**Comment by geofmureithi** [comment] 2024-07-02 20:16
Currently I have the register method able to work without clone. The issue though is when using register_with_count, I am trying to figure something. Will update in upcoming 0.6 releases.

**Comment by geofmureithi** [comment] 2024-07-04 18:35
This has been fixed by #348

**Closed by geofmureithi** 2024-07-04 18:35 UTC

**Comment by IgnisDa** [comment] 2024-07-05 03:37
@geofmureithi Thanks. Can you cut a new release?

**Comment by geofmureithi** [comment] 2024-07-05 04:29
There is v0.6.0-rc.1
