### ISSUE TITLE
Workers not acknowledging after upgrate to v0.4

### ISSUE THREAD

**Issue by samgj18** [geofmureithi/apalis#95] opened 2023-05-27 17:23 UTC
```json
{
    "job": null,
    "context": {
        "id": "JID-01H1F31FYEDKGH94XQEDX4ZSYA",
        "status": "Pending",
        "run_at": "2023-05-27T17:10:33.166137782Z",
        "attempts": 0,
        "max_attempts": 25,
        "last_error": null,
        "lock_at": null,
        "lock_by": null,
        "done_at": null
    }
}
```

```{"v":0,"name":"majinn","msg":"Sending email: EmailApalis","level":30,"hostname":"samuel","pid":87291,"time":"2023-05-27T17:10:32.792390087Z","line":23}```

I'm getting this from redis and the trace respectively. Any hints on what could be?

**Comment by geofmureithi** [comment] 2023-05-28 11:28
Could you share a simple working sample? Just with the needed parts.

**Comment by samgj18** [comment] 2023-05-28 13:32
Hey, is the exact same example as in the README. No difference at all. What might be interesting is that I'm racing it agains an actix-web server using `tokio::select!`, but I did the same for version 0.3 and worked.

**Comment by geofmureithi** [comment] 2023-05-28 14:23
What is the complete error? 

> ```Acknowledgement could not be called due to missing ack data in context .............................?```
This seems like the ack service is missing something in context

**Comment by bastienriviereocd** [comment] 2023-05-31 12:46
It can be reproduced by running the [redis example](https://github.com/geofmureithi/apalis/tree/master/examples/redis). Might be tied to the redis storage since it doesn't happen with the postgres storage.

Complete log:

```
2023-05-31T12:46:11.255706Z DEBUG apalis_redis::storage: Received new job with id: JID-01H1RXG9SQJRFPG2RZ39M6H3Z7 to list: apalis::Email:active
2023-05-31T12:46:11.308607Z DEBUG job{job_id="JID-01H1RXG9SQJRFPG2RZ39M6H3Z7" current_attempt=0}: apalis_core::layers::tracing::on_request: job.start
2023-05-31T12:46:11.308758Z  INFO job{job_id="JID-01H1RXG9SQJRFPG2RZ39M6H3Z7" current_attempt=0}: email_service: Attempting to send email to test@example.com
2023-05-31T12:46:11.308810Z  WARN job{job_id="JID-01H1RXG9SQJRFPG2RZ39M6H3Z7" current_attempt=0}: apalis_core::layers::ack: Acknowledgement could not be called due to missing ack data in context : apalis_core::job::JobId
2023-05-31T12:46:11.308857Z DEBUG job{job_id="JID-01H1RXG9SQJRFPG2RZ39M6H3Z7" current_attempt=0}: apalis_core::layers::tracing::on_response: job.done done_in=0ms result=()
```

**Comment by samgj18** [comment] 2023-05-31 14:32
Sorry I didn't have time to reproduce it as I moved forward with previous version, but tit was exactly the same error, thanks @bastienriviereocd

**Comment by geofmureithi** [comment] 2023-05-31 17:28
I will release a fix for this tonight--
Geoffrey Mureithi
+254713622599
mureithi.me
Skype: live:mureithinjuguna

**Closed** 2023-06-02 16:17 UTC
Labels: bug, redis
