### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by AzHicham** [geofmureithi/apalis#250] opened 2024-02-27 10:31 UTC
Hello, 

I'm using apalis with those specific feature flags: 
`apalis = { version = "^0.5.0", default-features = false, features = ["apalis-redis", "tokio-comp"] }`

But still in my Cargo.lock I found that apalis-sql cron are downloaded & build: 
Cargo.lock
```
[[package]]
name = "apalis"
version = "0.5.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "82fa3b6942555029a1c59174250602fefa15fe1ad761b5210db36ea7f402a999"
dependencies = [
 "apalis-core",
 "apalis-cron",
 "apalis-redis",
 "apalis-sql",
 "futures",
 "pin-project-lite",
 "serde",
 "thiserror",
 "tokio",
 "tower",
]
```

Before 0.5.0 a trick was to use apalis-core & apalis-redis instead of apalis. but now I need also to import TokioExecutor which is behind apalis 

The moment I enable `tokio-comp` redis, sql & cron are also enabled
Did I miss something ? or there is something wrong with this code : 
```
tokio-comp = [
    "apalis-sql?/tokio-comp",
    "apalis-redis?/tokio-comp",
    "apalis-cron?/tokio-comp",
    "tokio",
]
```

Thank you

**Comment by geofmureithi** [comment] 2024-02-27 13:41
This is noted, and I will look into it. This is not expected behaviour. Possibly because of `tokio-comp`

**Comment by geofmureithi** [comment] 2024-02-28 04:00
I can confirm that this is caused by including `tokio-comp`.
This is a priority issue.

> Before 0.5.0 a trick was to use apalis-core & apalis-redis instead of apalis. but now I need also to import TokioExecutor which is behind apalis

Meanwhile, a quick work-around with your previous approach can just be a custom implementation:
```
#[derive(Clone, Debug, Default)]
pub struct MyTokioExecutor;

impl apalis_core::executor::Executor for MyTokioExecutor {
    fn spawn(&self, future: impl std::future::Future<Output = ()> + Send + 'static) {
        tokio::spawn(future);
     }
}
```

**Comment by AzHicham** [comment] 2024-02-28 09:53
Nice I'll try that

**Comment by AzHicham** [comment] 2024-03-17 14:29
Hello, 
I was thinking since the refactoring with version 0.5.0, is it really necessary to have separate crate instead of featured mod in the main crate ? 
I'm saying this because it may allow to fix this issue :)

**Comment by geofmureithi** [comment] 2024-03-18 18:28
True true. Will be so in 0.6

**Comment by geofmureithi** [comment] 2024-07-10 08:09
Resolved by https://github.com/geofmureithi/apalis/pull/357

**Closed by geofmureithi** 2024-07-10 08:09 UTC
Labels: bug
